### ISSUE TITLE
Identity SDK is gone?

### ISSUE THREAD

**Issue by jeanlucmongrain** [onchain-id/documentation#22]
`developers/sdk/get-started.md` refers to:

```js
import { IdentitySDK } from '@onchain-id/identity-sdk'
```

which is [this NPM package](https://www.npmjs.com/package/@onchain-id/identity-sdk)

that link to [this repository](https://github.com/onchain-id/identity-sdk) that 404.

Where is the source code of the SDK?

**Comment by Joachim-Lebrun** [comment]
The identity SDK source code is on a private repository right now, but the dependency is available publicly, we should make the SDK source code public soon
